- name: variables from taks level
  hosts: localhost
  tasks:
    - name: Inserting vars
      vars:
        Name: "GOOGLE"
        site: "techytrees"
      ansible.builtin.debug:
        msg: "Hi {{Name}}, Welcome to {{site}}"