- name: variables from inventory & args
  hosts: localhost
  tasks:
    - name: variables checking
      ansible.builtin.debug:
        #msg: "Hi {{NAME}}, wellcome to {{SITE}}" #from args
        msg: "Hi {{name}}, wellcome to {{site}}"