- name: Variables from PLAY
  hosts: localhost
  var:
    Fisrt_Name: "Rajesh"
    Second_Name: "Chanti"
    AGE: "29 yrs"
  tasks:
    - name: Inserting Vars
      ansible.builtin.debug:
        msg: "Hi, Wellcome {{First_Name}} {{Second_Name}} {{AGE}}"